server:
  port: 80
debug: false
logging:
  level:
    root: info
  file: /local/user/app-prd.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://219.229.162.55:3304/prd
    username: root1
    password: 17541ee6
mail:
  config:
    name: 优美商城
    description: 这是一家化妆品特卖网站
    hot-sales: 20
    show-advert: true